CREATE TABLE TB_CODE_GROUP (
    GROUP_CODE VARCHAR2(50) NOT NULL,
    GROUP_NAME VARCHAR2(50) NOT NULL,
    DESCRIPTION VARCHAR2(500) NOT NULL,
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CREATED_BY VARCHAR2(100) NOT NULL,
    UPDATED_AT TIMESTAMP,
    UPDATED_BY VARCHAR2(100),

    CONSTRAINT PK_TB_CODE_GROUP PRIMARY KEY (GROUP_CODE)
);

CREATE TABLE TB_COMMON_CODE (
    GROUP_CODE VARCHAR2(50) NOT NULL,
    COMMON_CODE VARCHAR2(50) NOT NULL,
    CODE_NAME VARCHAR2(100) NOT NULL,
    USE_YN CHAR(1) DEFAULT 'Y' NOT NULL,
    DEL_YN CHAR(1) DEFAULT 'N' NOT NULL,
    SORT_ORDER NUMBER(5) NOT NULL,
    DESCRIPTION VARCHAR2(500) NOT NULL,
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CREATED_BY VARCHAR2(100) NOT NULL,
    UPDATED_AT TIMESTAMP,
    UPDATED_BY VARCHAR2(100),

    CONSTRAINT PK_TB_COMMON_CODE PRIMARY KEY (GROUP_CODE, COMMON_CODE),
    CONSTRAINT FK_TB_COMMON_GROUP_CODE FOREIGN KEY (GROUP_CODE) REFERENCES TB_CODE_GROUP (GROUP_CODE),
    CONSTRAINT CK_TB_COMMON_CODE_USE_YN CHECK (USE_YN IN ('Y', 'N')),
    CONSTRAINT CK_TB_COMMONM_CODE_DEL_YN CHECK (DEL_YN IN ('Y', 'N') )
);

CREATE TABLE TB_ACCOUNT (
    ACCOUNT_NUMBER VARCHAR2(30) NOT NULL,
    ACCOUNT_OWNER VARCHAR2(50) NOT NULL,
    ACCOUNT_TYPE_GROUP_CODE VARCHAR2(50) NOT NULL,
    ACCOUNT_TYPE_CODE VARCHAR2(50) NOT NULL,
    BANK_GROUP_CODE VARCHAR2(50) NOT NULL,
    BANK_CODE VARCHAR2(50) NOT NULL,
    USE_YN CHAR(1) DEFAULT 'Y' NOT NULL,
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CREATED_BY VARCHAR2(100) NOT NULL,
    UPDATED_AT TIMESTAMP,
    UPDATED_BY VARCHAR2(100),

    CONSTRAINT PK_TB_ACCOUNT PRIMARY KEY (ACCOUNT_NUMBER),
    CONSTRAINT FK_TB_ACCOUNT_TYPE FOREIGN KEY (ACCOUNT_TYPE_GROUP_CODE, ACCOUNT_TYPE_CODE)
                        REFERENCES TB_COMMON_CODE (GROUP_CODE, COMMON_CODE),
    CONSTRAINT FK_TB_BANK_CODE FOREIGN KEY (BANK_GROUP_CODE, BANK_CODE)
                        REFERENCES TB_COMMON_CODE (GROUP_CODE, COMMON_CODE),
    CONSTRAINT CK_TB_ACCOUNT_USE_YN CHECK (USE_YN IN ('Y', 'N'))
);