CREATE TABLE TB_CODE_GROUP (
    GROUP_CODE VARCHAR2(50) NOT NULL,
    GROUP_NAME VARCHAR2(50) NOT NULL,
    DESCRIPTION VARCHAR2(500) NOT NULL,
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CREATED_BY VARCHAR2(100) NOT NULL,
    UPDATED_AT TIMESTAMP,
    UPDATED_BY VARCHAR2(100),

    CONSTRAINT PK_TB_CODE_GROUP PRIMARY KEY (GROUP_CODE)
);

CREATE TABLE TB_COMMON_CODE (
    GROUP_CODE VARCHAR2(50) NOT NULL,
    COMMON_CODE VARCHAR2(50) NOT NULL,
    CODE_NAME VARCHAR2(100) NOT NULL,
    USE_YN CHAR(1) DEFAULT 'Y' NOT NULL,
    SORT_ORDER NUMBER(5) NOT NULL,
    DESCRIPTION VARCHAR2(500) NOT NULL,
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CREATED_BY VARCHAR2(100) NOT NULL,
    UPDATED_AT TIMESTAMP,
    UPDATED_BY VARCHAR2(100),

    CONSTRAINT PK_TB_COMMON_CODE PRIMARY KEY (GROUP_CODE, COMMON_CODE),
    CONSTRAINT FK_TB_COMMON_GROUP_CODE FOREIGN KEY (GROUP_CODE) REFERENCES TB_CODE_GROUP (GROUP_CODE),
    CONSTRAINT CK_TB_COMMON_CODE_USE_YN CHECK (USE_YN IN ('Y', 'N'))
);